apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch-api-test
  labels:
    app: scratch-api-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scratch-api-test
  template:
    metadata:
      labels:
        app: scratch-api-test
    spec:
      dnsPolicy: Default
      containers:
      - name: scratch-api-test
        image: scratch-api-test
        envFrom:
          - secretRef:
              name: scratch-api-test-readonly #environment variables should be created in secrets
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: 1G
            cpu: 50m
          limits:
            memory: 2G
            cpu: 100m
        volumeMounts:
        - name: log-volume
          mountPath: /data/logs
      - name: fluentbit
        image: fluent/fluent-bit:1.6-debug
        resources:
          requests:
            memory: 200M
            cpu: 10m
          limits:
            memory: 250M
            cpu: 20m
        volumeMounts:
        - name: log-volume
          mountPath: /data/logs
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: config
        configMap:
          name: fluentbit-configmap-scratch-api-test

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-configmap-scratch-api-test
  labels:
    component: fluentbit-configmap-scratch-api-test
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name             tail
        Path             /data/logs/scratch-api-test-info.log
        Multiline        off
        Buffer_Max_Size  128k


    [OUTPUT]
        Name  es
        Match *
        Host  logs.scratchpay.com
        Port  9200
        Logstash_Format On
        Retry_Limit False
        Trace_Output On
        Time_Key @timestamp
        Logstash_Prefix scratch-api-test-production
        Index scratch-api-test-production

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scratch-api-test
  name: scratch-api-test
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000
  selector:
    app: scratch-api-test
  type: NodePort

