version: "3.9"
services:
  api:
    build: .
    links:
      - "mysql:database"
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:password@mysql:3306/users'
      ENVIRONMENT: 'production'
    restart: on-failure

  mysql:
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: web
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db:/etc/mysql/conf.d
    image: "mysql/mysql-server"
